### ISSUE TITLE
Draft WLOH study on main site, extend "datareturn" site to integrate with this

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/open-humans#257]
The "datareturn" site can be used to return data (in the form of files or links) to users: https://github.com/PersonalGenomesOrg/datareturn

Our current motivation is to use this to give data access to participants from Wild Life of Our Homes and enable them to connect it to their PGP data through Open Humans. To do this, we need to extend this site to allow a Open Humans integration, and Open Humans to accept that. Current plan is to do this with the "datareturn" as a "data-push" provider (i.e. use Open Humans as the OAuth2 provider, push data to Open Humans).

**Comment by madprime** [comment]
Partly done - datareturn has draft code for integrating with Open Humans.

**Comment by beaugunderson** [comment]
thoughts:

- can OpenHumansConfig not be a model? (keeps client ID/secret out of the database)
- it seems like sites using `datareturn` to manage their data are going to be small and/or one-off efforts; because of this I think we can handle them all with one DataFile with multiple subtypes... does that sound possible?
- if that's the case I think we can create separate OAuth2 Application objects for each datareturn site and they can all use the same URLs, but specify different subtypes
- the Application could also be tied to the DataFile with an intermediary model that contains the text description from the datareturn site (though maybe that's an optimization we don't really need)

**Comment by madprime** [comment]
Re "not a model" I think env for secrets makes sense. I was trying to make it easy to set up, and some aspects (like a paragraph of markdown formatted text) are too much for env.

Regarding same-DataFile: I have lots of reservations. I want to see an abstract treatment of connected studies instead of continuing to make new apps, but I think it needs to be done with lots of thought & rewrite existing studies to use it (if/where possible). Otherwise we risk creating yet another different behavior we need to be keeping track of – if a "simplification" never gets re-used, and we're actually just making things even more complex.

**Comment by beaugunderson** [comment]
Goal here for the integration is to get an Open Humans user through the process through the process to data processing, and have data processing will respond with a `200 OK`.
